site_name: test

nav:
    - Index: index.md
    - Code: index2.md

theme:
    name: 'material'
    language: 'ja'

extra:
    language: 'jp'

markdown_extensions:
    - toc:
        permalink: true
        slugify: !!python/name:pymdownx.slugs.uslugify
