site_name: adstir Integration Guide for Android

site_url: https://yuji-morita.github.io/action-test

nav:
  - ガイド:
    - Index: index.md
    - Index2: index2.md
    - Index3: index3.md
    - Index4: index4.md
  - リファレンス:
    - Index: reference.md

theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true
  custom_dir: 'custom_dir'
  logo: 'img/favicon.ico'

extra_css:
  - 'css/custom.css'

extra:
    language: 'jp'

markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - meta
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.details
